# fly.toml app configuration file generated for lnmb on 2023-11-01T08:58:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lnmb"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
